### ISSUE TITLE
DB_TYPE_OBJECT issue

### ISSUE THREAD

**Issue by ahmed-r-hashim** [oracle/python-oracledb#106]
It seems that the recent package (v1.2.0) contains a regression/typo bug,
\Python310\lib\site-packages\oracledb\dbobject.py", line 42, in __getattr__
    attr_impl = self._impl.type.attrs_by_name[name]

quick fix ;)
`attr_impl = self._impl._type.attrs_by_name[name]`

I wanted to submit a PR, but bureaucracy did stop me in the middle of my journey.

**Comment by cjbj** [comment]
Thanks for the report.

**Comment by anthony-tuininga** [comment]
Can you explain under what circumstances you get an error? The line in question appears to be correct to my mind. Since this line is used for every object attribute access I don't think it could be missed if it doesn't work! So there must be some scenario tht is missing. Can you supply that scenario, please? Thank you!

**Comment by anthony-tuininga** [comment]
Since no response is forthcoming I will close this issue. If you are able to supply the full traceback and a test case, though, please do so and re-open!

**Comment by aimanaziz1993** [comment]
I would like to highlight this issue since it has occur again to me.

So, the scenario was I am constructing a spatial column geometry data and use get attribute with the thick mode are True. It has MDSYS.SDO_GEOMETRY of oracle.DdObject

The exception was:
myvenv/lib/python3.10/site-packages/oracledb/dbobject.py", line 48, in __getattr__
    attr_impl = self._impl.type.attrs_by_name[name]
KeyError: '_typ'

I tried to use the quick fix as mentioned above, and the exception now return:
AttributeError: 'oracledb.thick_impl.ThickDbObjectImpl' object has no attribute '_type'. Did you mean: 'type'?

**Comment by anthony-tuininga** [comment]
What version of the driver are you using? There was a change in version 2.0.0 that may have addressed this -- or at least would result in a better error! If you are indeed using version 2.0.0 or 2.0.1 already, then please open a new issue with information on how to reproduce the issue. Thanks!

**Comment by aimanaziz1993** [comment]
> What version of the driver are you using? There was a change in version 2.0.0 that may have addressed this -- or at least would result in a better error! If you are indeed using version 2.0.0 or 2.0.1 already, then please open a new issue with information on how to reproduce the issue. Thanks!

The driver used for oracledb is, oracledb==1.4.2
