### ISSUE TITLE
wheel file for python 3.6 (windows)

### ISSUE THREAD

**Issue by mgutierrezp** [oracle/python-oracledb#110]
1. Describe your new request in detail
-> could you please add a precompiled wheel for windows environment (x64) and python 3.6?
2. Give supporting information about tools and operating systems.  Give relevant product version numbers

**Comment by anthony-tuininga** [comment]
Python 3.6 reached end-of-life almost a year ago (December 2021) and as such it is strongly recommended to upgrade to a newer version of Python.

**Comment by mgutierrezp** [comment]
thanks for the reply. I suspected that. Unfortunately, upgrading python on my environment is not an easy task. Thanks for the prompt reply, though. Regards

**Comment by anthony-tuininga** [comment]
If you're wondering why binaries for Python 3.6 are available for Linux, that is solely because these platforms (specifically Red Hat and Oracle) have at least partial ongoing support -- whereas Windows does not. You can, of course, build binaries yourself, but I understand that can be painful on Windows. :-)

**Comment by mgutierrezp** [comment]
...it is in fact :) No worries. Thanks again
