### ISSUE TITLE
create_pool_async requires asyncio and causes issues in pytest_asyncio

### ISSUE THREAD

**Issue by WolfEYc** [oracle/python-oracledb#309]
1. What versions are you using?
2.1.0

    19c
    
    platform.platform: macOS-14.3.1-arm64-arm-64bit
    sys.maxsize > 2**32: True
    platform.python_version: 3.12.2
    
    oracledb.__version__: 2.1.0

2. Is it an error or a hang or a crash?
hang

3. What error(s) or behavior you are seeing?
pool.aquire() hangs when used in context of async pytest of FastAPI app

4. Does your application call init_oracle_client()?
No

5. Include a runnable Python script that shows the problem.
https://gist.github.com/WolfEYc/90a1f994fee007729037ef62de99e753
run pytest on this script and make sure to have the following python pkgs installed and in most recent ver
asgi-lifespan 
httpx
pytest
pytest-asyncio
fastapi
and ofc oracledb 2.1.0

dont need any sql as it is not a sql related error, it is a connection error.

for reference, when running the app normally it works just fine! but pytest it hangs indefinitley @anthony-tuininga

**Comment by anthony-tuininga** [comment]
Hmm, something else is going on. Just for interest I changed the create_pool_async() call to be marked as async def and the test *still* hangs. Debugging shows that the "hang" occurs during the *first* attempt to perform an await. If you hit Ctrl-C the code continues until the cleanup operation takes place. So this would seem to be something with the pytest machinery or the test case in particular and not an issue with the create_pool_async() method at all! If you have other evidence that suggests otherwise, please let me know!

**Comment by WolfEYc** [comment]
@cjbj My singleton workaround mitigates the issue.
