### ISSUE TITLE
Var.outconverter() is not writable

### ISSUE THREAD

**Issue by leo-b** [oracle/python-oracledb#360]
Hi!

The latest oracledb documentation states that `Variable.outconverter` is a read-write attribute.
https://python-oracledb.readthedocs.io/en/latest/api_manual/variable.html#Variable.outconverter

However this doesn't seem to be true:

```
v = cursor.var(oracledb.DB_TYPE_NUMBER)
v.outconverter = lambda x: x
# AttributeError: property 'outconverter' of 'Var' object has no setter
```

Is the setter property missing or is the documentation wrong?

Cheers,
--leo

**Comment by cjbj** [comment]
We'll review; thanks.

**Comment by anthony-tuininga** [comment]
Since this method is called internally during cursor execution, having it changed midstream could make the results difficult to predict. I'll change the documentation to indicate that it is read-only -- but if you would like the ability to set this (and its sibliing inconverter), please provide the reason you would like to do so! Thanks.

**Comment by anthony-tuininga** [comment]
The documentation has been updated. Thanks for bringing this to our attention!
